// Code generated by go-swagger; DO NOT EDIT.

package market_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alien45/bridge-api/models"
)

// AddOrderOKCode is the HTTP code returned for type AddOrderOK
const AddOrderOKCode int = 200

/*AddOrderOK Order inserted successfully

swagger:response addOrderOK
*/
type AddOrderOK struct {
}

// NewAddOrderOK creates AddOrderOK with default headers values
func NewAddOrderOK() *AddOrderOK {
	return &AddOrderOK{}
}

// WriteResponse to the client
func (o *AddOrderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddOrderBadRequestCode is the HTTP code returned for type AddOrderBadRequest
const AddOrderBadRequestCode int = 400

/*AddOrderBadRequest Invalid request

swagger:response addOrderBadRequest
*/
type AddOrderBadRequest struct {
}

// NewAddOrderBadRequest creates AddOrderBadRequest with default headers values
func NewAddOrderBadRequest() *AddOrderBadRequest {
	return &AddOrderBadRequest{}
}

// WriteResponse to the client
func (o *AddOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddOrderUnprocessableEntityCode is the HTTP code returned for type AddOrderUnprocessableEntity
const AddOrderUnprocessableEntityCode int = 422

/*AddOrderUnprocessableEntity Validation exception

swagger:response addOrderUnprocessableEntity
*/
type AddOrderUnprocessableEntity struct {
}

// NewAddOrderUnprocessableEntity creates AddOrderUnprocessableEntity with default headers values
func NewAddOrderUnprocessableEntity() *AddOrderUnprocessableEntity {
	return &AddOrderUnprocessableEntity{}
}

// WriteResponse to the client
func (o *AddOrderUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

/*AddOrderDefault unexpected error

swagger:response addOrderDefault
*/
type AddOrderDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewAddOrderDefault creates AddOrderDefault with default headers values
func NewAddOrderDefault(code int) *AddOrderDefault {
	if code <= 0 {
		code = 500
	}

	return &AddOrderDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add order default response
func (o *AddOrderDefault) WithStatusCode(code int) *AddOrderDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add order default response
func (o *AddOrderDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add order default response
func (o *AddOrderDefault) WithPayload(payload *models.ErrorResponse) *AddOrderDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add order default response
func (o *AddOrderDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOrderDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
