// Code generated by go-swagger; DO NOT EDIT.

package market_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/alien45/bridge-api/models"
)

// NewAddOrderParams creates a new AddOrderParams object
// with the default values initialized.
func NewAddOrderParams() AddOrderParams {
	var ()
	return AddOrderParams{}
}

// AddOrderParams contains all the bound params for the add order operation
// typically these are obtained from a http.Request
//
// swagger:parameters addOrder
type AddOrderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Order object that needs to be added to the order book
	  In: body
	*/
	Order *models.Order
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddOrderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Order
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("order", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Order = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
