// Code generated by go-swagger; DO NOT EDIT.

package market_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CancelOrderHandlerFunc turns a function with the right signature into a cancel order handler
type CancelOrderHandlerFunc func(CancelOrderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CancelOrderHandlerFunc) Handle(params CancelOrderParams) middleware.Responder {
	return fn(params)
}

// CancelOrderHandler interface for that can handle valid cancel order params
type CancelOrderHandler interface {
	Handle(CancelOrderParams) middleware.Responder
}

// NewCancelOrder creates a new http.Handler for the cancel order operation
func NewCancelOrder(ctx *middleware.Context, handler CancelOrderHandler) *CancelOrder {
	return &CancelOrder{Context: ctx, Handler: handler}
}

/*CancelOrder swagger:route DELETE /market/orders/{order_id} Market Access cancelOrder

Cancel the order by ID

*/
type CancelOrder struct {
	Context *middleware.Context
	Handler CancelOrderHandler
}

func (o *CancelOrder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCancelOrderParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
