// Code generated by go-swagger; DO NOT EDIT.

package market_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alien45/bridge-api/models"
)

// GetSymbolsOKCode is the HTTP code returned for type GetSymbolsOK
const GetSymbolsOKCode int = 200

/*GetSymbolsOK successful operation

swagger:response getSymbolsOK
*/
type GetSymbolsOK struct {

	/*
	  In: Body
	*/
	Payload models.GetSymbolsOKBody `json:"body,omitempty"`
}

// NewGetSymbolsOK creates GetSymbolsOK with default headers values
func NewGetSymbolsOK() *GetSymbolsOK {
	return &GetSymbolsOK{}
}

// WithPayload adds the payload to the get symbols o k response
func (o *GetSymbolsOK) WithPayload(payload models.GetSymbolsOKBody) *GetSymbolsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get symbols o k response
func (o *GetSymbolsOK) SetPayload(payload models.GetSymbolsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSymbolsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetSymbolsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetSymbolsDefault unexpected error

swagger:response getSymbolsDefault
*/
type GetSymbolsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetSymbolsDefault creates GetSymbolsDefault with default headers values
func NewGetSymbolsDefault(code int) *GetSymbolsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSymbolsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get symbols default response
func (o *GetSymbolsDefault) WithStatusCode(code int) *GetSymbolsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get symbols default response
func (o *GetSymbolsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get symbols default response
func (o *GetSymbolsDefault) WithPayload(payload *models.ErrorResponse) *GetSymbolsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get symbols default response
func (o *GetSymbolsDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSymbolsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
