// Code generated by go-swagger; DO NOT EDIT.

package market_access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/alien45/bridge-api/models"
)

// GetExchangesOKCode is the HTTP code returned for type GetExchangesOK
const GetExchangesOKCode int = 200

/*GetExchangesOK successful operation

swagger:response getExchangesOK
*/
type GetExchangesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetExchangesOKBody `json:"body,omitempty"`
}

// NewGetExchangesOK creates GetExchangesOK with default headers values
func NewGetExchangesOK() *GetExchangesOK {
	return &GetExchangesOK{}
}

// WithPayload adds the payload to the get exchanges o k response
func (o *GetExchangesOK) WithPayload(payload models.GetExchangesOKBody) *GetExchangesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get exchanges o k response
func (o *GetExchangesOK) SetPayload(payload models.GetExchangesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExchangesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetExchangesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetExchangesDefault unexpected error

swagger:response getExchangesDefault
*/
type GetExchangesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetExchangesDefault creates GetExchangesDefault with default headers values
func NewGetExchangesDefault(code int) *GetExchangesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetExchangesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get exchanges default response
func (o *GetExchangesDefault) WithStatusCode(code int) *GetExchangesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get exchanges default response
func (o *GetExchangesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get exchanges default response
func (o *GetExchangesDefault) WithPayload(payload *models.ErrorResponse) *GetExchangesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get exchanges default response
func (o *GetExchangesDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExchangesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
