// Code generated by go-swagger; DO NOT EDIT.

package account_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetLinkedAccountsHandlerFunc turns a function with the right signature into a get linked accounts handler
type GetLinkedAccountsHandlerFunc func(GetLinkedAccountsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLinkedAccountsHandlerFunc) Handle(params GetLinkedAccountsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLinkedAccountsHandler interface for that can handle valid get linked accounts params
type GetLinkedAccountsHandler interface {
	Handle(GetLinkedAccountsParams, interface{}) middleware.Responder
}

// NewGetLinkedAccounts creates a new http.Handler for the get linked accounts operation
func NewGetLinkedAccounts(ctx *middleware.Context, handler GetLinkedAccountsHandler) *GetLinkedAccounts {
	return &GetLinkedAccounts{Context: ctx, Handler: handler}
}

/*GetLinkedAccounts swagger:route GET /accounts Account Data getLinkedAccounts

Return the list of all the linked accounts

*/
type GetLinkedAccounts struct {
	Context *middleware.Context
	Handler GetLinkedAccountsHandler
}

func (o *GetLinkedAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetLinkedAccountsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
