// Code generated by go-swagger; DO NOT EDIT.

package account_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Guruvest/bridge-api/models"
)

// GetLinkedAccountsOKCode is the HTTP code returned for type GetLinkedAccountsOK
const GetLinkedAccountsOKCode int = 200

/*GetLinkedAccountsOK successful operation

swagger:response getLinkedAccountsOK
*/
type GetLinkedAccountsOK struct {

	/*
	  In: Body
	*/
	Payload models.GetLinkedAccountsOKBody `json:"body,omitempty"`
}

// NewGetLinkedAccountsOK creates GetLinkedAccountsOK with default headers values
func NewGetLinkedAccountsOK() *GetLinkedAccountsOK {
	return &GetLinkedAccountsOK{}
}

// WithPayload adds the payload to the get linked accounts o k response
func (o *GetLinkedAccountsOK) WithPayload(payload models.GetLinkedAccountsOKBody) *GetLinkedAccountsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get linked accounts o k response
func (o *GetLinkedAccountsOK) SetPayload(payload models.GetLinkedAccountsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinkedAccountsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetLinkedAccountsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetLinkedAccountsDefault unexpected error

swagger:response getLinkedAccountsDefault
*/
type GetLinkedAccountsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetLinkedAccountsDefault creates GetLinkedAccountsDefault with default headers values
func NewGetLinkedAccountsDefault(code int) *GetLinkedAccountsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLinkedAccountsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get linked accounts default response
func (o *GetLinkedAccountsDefault) WithStatusCode(code int) *GetLinkedAccountsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get linked accounts default response
func (o *GetLinkedAccountsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get linked accounts default response
func (o *GetLinkedAccountsDefault) WithPayload(payload *models.ErrorResponse) *GetLinkedAccountsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get linked accounts default response
func (o *GetLinkedAccountsDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinkedAccountsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
