// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Guruvest Bridge API
The Guruvest Bridge API is a REST API served the Guruvest platform. It is the API that third party client uses to communicate signals to the Guruvest platform.

# Errors

The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:

```
{
  "message": "page not found"
}
```

# Versioning

The API is usually changed in each release, so API calls are versioned to
ensure that clients don't break. To lock to a specific version of the API,
you prefix the URL with its version, for example, call `/v0/info` to use
the v0 version of the `/info` endpoint. If the API version specified in
the URL is not supported by the daemon, a HTTP `400 Bad Request` error message
is returned.

If you omit the version-prefix, the current version of the API (v1) is used.
For example, calling `/info` is the same as calling `/v1/info`. Using the
API without a version-prefix is deprecated and will be removed in a future release.

The API uses an open schema model, which means server may add extra properties
to responses. Likewise, the server will ignore any extra query parameters and
request body properties. When you write clients, you need to ignore additional
properties in responses to ensure they do not break when talking to newer
daemons.


```



    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
