// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Tick tick
// swagger:model Tick
type Tick struct {

	// ask
	Ask float32 `json:"ask,omitempty"`

	// bid
	Bid float32 `json:"bid,omitempty"`

	// current volume
	CurrentVolume float32 `json:"current_volume,omitempty"`

	// The code of the exchange/broker
	ExchangeCode string `json:"exchange_code,omitempty"`

	// high
	High float32 `json:"high,omitempty"`

	// last
	Last float32 `json:"last,omitempty"`

	// low
	Low float32 `json:"low,omitempty"`

	// The symbol of an asset
	Symbol string `json:"symbol,omitempty"`

	// The full date time format ISO 8601 from the exchange/broker
	Timestamp strfmt.DateTime `json:"timestamp,omitempty"`
}

// Validate validates this tick
func (m *Tick) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Tick) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tick) UnmarshalBinary(b []byte) error {
	var res Tick
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
